### ISSUE TITLE
vs. URLSearchParams

### ISSUE THREAD

**Issue by MarkTiedemann** [denolib/qs#3]
Deno already supports [`URLSearchParams`](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams) which can be used to parse and stringify a query string.

```
$ deno
> new URLSearchParams("a=1&b=2")
URLSearchParams { params: [ [ "a", "1" ], [ "b", "2" ] ], url: null }
> q = new URLSearchParams(); q.set("a", 1); q.set("b", 2); q.toString()
a=1&b=2
```

So, is this module actually necessary? What does it do differently then `URLSearchParams`? How does it hold up in benchmarks? Could the module be re-written to use `URLSearchParams` internally?

**Comment by kevinkassimo** [comment]
https://github.com/ljharb/qs/issues/319

**Comment by MarkTiedemann** [comment]
@kevinkassimo I think there are 2 arguments made in that issue.

1. `URLSearchParams` is not supported in all browsers yet ([92%](https://caniuse.com/#search=urlsearchparams)), and a polyfill would increase bundle size. However, I don't think this argument applies to Deno - the polyfill isn't needed since Deno ships with `URLSearchParams`.

2. Support for nesting, e.g. `{ a: 1, b: { c: 2 } } => a=1&b[c]=2`, as a feature that `URLSearchParams` doesn't support.

Might be good to add a section to the `README.md` to clarify use-cases for `qs` vs. `URLSearchParams`.
